name: Flask App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        pip install vosk
        pip install flask
        pip install pymongo
        pip install flask_cors
        pip install rapidfuzz
    
    - name: Download Vosk model
      run: |
        mkdir -p vosk-model-small-en-us-0.15
        curl -L https://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip -o model.zip
        unzip model.zip
        mv vosk-model-small-en-us-0.15/* vosk-model-small-en-us-0.15/
    
    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: '6.0'
    
    - name: Run tests
      run: |
        pytest tests/